name: Go Status
on: [push, pull_request]
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.24
        uses: actions/setup-go@v1
        with:
          go-version: 1.24
        id: go
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
      - name: check contents table
        run: |
          go test ./...
